FROM python:3.10
WORKDIR /app
COPY backend/dependencies.txt .


RUN pip install virtualenv
RUN virtualenv venv


RUN . venv/bin/activate && pip install -r dependencies.txt

COPY backend/ .
ARG DJANGO_SECRET_KEY
ARG FRONTEND_URL
ENV DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
ENV FRONTEND_URL=$FRONTEND_URL
EXPOSE 8000 

RUN . venv/bin/activate && python manage.py migrate

CMD [ "python","manage.py","runserver","127.0.0.1:8000"]