FROM python:3
WORKDIR /app
COPY backend/dependencies.txt .
RUN pip install -r dependencies.txt

COPY backend/ .
RUN python manage.py migrate
EXPOSE 8000
CMD [ "python","manage.py","runserver","0.0.0.0:8000"]